language : cpp
env:
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.7
    - source qt-5.7.env
    - mkdir build
    - cd build
    - run-unittests ../tests/qtshellunittests/qtshellunittests.pro

