language : cpp
env:
  - DISPLAY=:99.0
compiler:
  - gcc
before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt532
    - sudo add-apt-repository --yes "deb http://download.opensuse.org/repositories/home:/benlau/xUbuntu_15.10 ./"
    - sudo apt-get update -qq
    - apt-cache search qt5
    - sudo apt-get install --force-yes -qq qt53quickcontrols  qt53declarative qt53script qt53graphicaleffects qpm
    - sudo apt-get install nodejs
    - sh -e /etc/init.d/xvfb start
script:
    - source /opt/qt53/bin/qt53-env.sh
    - cd tests/qtshellunittests/
    - qmake
    - make
    - ls
    - ./unittests

